export const arrayGroupData = {
  content: [
    {
      rolloutId: 39,
      status: 'RUNNING',
      startTs: [2026, 9, 4, 8, 5],
      endedTs: null,
      stages: [
        {
          stageId: 49,
          sequenceNo: 1,
          blockCodes: ['CN101', 'LN1030139'],
          sheduledTs: [2026, 9, 4, 8, 5],
          status: 'FAILED',
          finishedTs: [2026, 9, 4, 8, 5],
          errorReason: 'Нет серверов для отправки',
        },
        {
          stageId: 50,
          sequenceNo: 2,
          blockCodes: ['LN103'],
          sheduledTs: [2026, 9, 4, 8, 5],
          status: 'FAILED',
          finishedTs: [2026, 9, 4, 8, 5],
          errorReason: 'Нет серверов для отправки',
        },
      ],
    },
    {
      rolloutId: 38,
      status: 'RUNNING',
      startTs: [2026, 9, 4, 8, 5],
      endedTs: null,
      stages: [
        {
          stageId: 46,
          sequenceNo: 1,
          blockCodes: ['LN003'],
          sheduledTs: [2026, 9, 4, 8, 5],
          status: 'PROCESSING',
          finishedTs: null,
          errorReason: null,
        },
        {
          stageId: 50,
          sequenceNo: 2,
          blockCodes: ['LN103'],
          sheduledTs: [2026, 9, 4, 8, 5],
          status: 'FAILED',
          finishedTs: [2026, 9, 4, 8, 5],
          errorReason: 'Нет серверов для отправки',
        },
      ],
    },
  ],
  pageable: {
    pageNumber: 0,
    pageSize: 20,
    sort: {
      sorted: true,
      empty: false,
      unsorted: false,
    },
    offset: 0,
    paged: true,
    unpaged: false,
  },
  last: true,
  totalPages: 1,
  totalElements: 2,
  size: 10,
  first: true,
  numberElements: 2,
  empty: false,
};
